# Generated by Django 5.0.2 on 2024-02-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tasks_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='is_completed',
            new_name='status',
        ),
    ]
